from setuptools import setup, find_packages

setup(
    name="chart_insights_system",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "python-dotenv>=1.0.0",
        "pyyaml>=6.0",
        "openai>=1.0.0",
        "langchain>=0.1.0",
        "llama-index>=0.8.0",
        "neo4j>=5.8.0",
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.14.0",
        "networkx>=3.0",
        "opencv-python>=4.7.0",
        "spacy>=3.5.0",
        "streamlit>=1.25.0",
        "fastapi>=0.100.0",
    ],
    python_requires=">=3.10",
    author="Your Name",
    author_email="your.email@example.com",
    description="Automated Chart Insights Generation System using GraphRAG",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3.10",
    ],
)
